// frontend/src/pages/admin/Stats.jsx
import { useEffect, useState } from 'react'
import { adminApi } from '../../api'
import StatCard from '../../components/StatCard'
import { BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, ResponsiveContainer } from 'recharts'
import { Users, Globe, Megaphone, LayoutGrid, Eye, MousePointerClick, DollarSign, TrendingUp } from 'lucide-react'

export default function AdminStats() {
  const [stats, setStats] = useState(null)

  useEffect(() => { adminApi.getStats().then((r) => setStats(r.data)) }, [])

  if (!stats) return (
    <div className="animate-pulse space-y-4">
      <div className="h-8 bg-gray-200 rounded w-48" />
      <div className="grid grid-cols-4 gap-4">{[...Array(8)].map((_, i) => <div key={i} className="h-24 bg-gray-200 rounded-2xl" />)}</div>
    </div>
  )

  const revenueData = [
    { name: 'Platform (10%)', value: Number(stats.totalPlatformRevenue) },
    { name: 'Network (20%)', value: Number(stats.totalNetworkRevenue) },
    { name: 'Publisher (70%)', value: Number(stats.totalNetworkRevenue) * 3.5 },
  ]

  return (
    <div className="space-y-6">
      <div>
        <h1 className="page-title">Platform Statistics</h1>
        <p className="text-sm text-gray-500 mt-0.5">Real-time overview of the AdSphere platform</p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <StatCard label="Total Users" value={stats.totalUsers} icon={Users} color="indigo" />
        <StatCard label="Total Websites" value={stats.totalWebsites} icon={Globe} color="cyan" />
        <StatCard label="Total Campaigns" value={stats.totalCampaigns} icon={Megaphone} color="amber" />
        <StatCard label="Total Placements" value={stats.totalPlacements} icon={LayoutGrid} color="violet" />
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <StatCard label="Total Impressions" value={Number(stats.totalImpressions).toLocaleString()} icon={Eye} color="indigo" />
        <StatCard label="Total Clicks" value={Number(stats.totalClicks).toLocaleString()} icon={MousePointerClick} color="emerald" />
        <StatCard label="Platform Revenue" value={`$${Number(stats.totalPlatformRevenue).toFixed(4)}`} icon={DollarSign} color="rose" />
        <StatCard label="Network Revenue" value={`$${Number(stats.totalNetworkRevenue).toFixed(4)}`} icon={TrendingUp} color="violet" />
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <div className="card p-6">
          <h2 className="section-title mb-4">Revenue Distribution</h2>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={revenueData} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 11, fill: '#9ca3af' }} tickLine={false} axisLine={false} tickFormatter={(v) => `$${v.toFixed(4)}`} />
              <YAxis type="category" dataKey="name" tick={{ fontSize: 11, fill: '#6b7280' }} tickLine={false} axisLine={false} width={100} />
              <Tooltip formatter={(v) => [`$${Number(v).toFixed(4)}`, 'Revenue']} contentStyle={{ borderRadius: 12, fontSize: 12 }} />
              <Bar dataKey="value" fill="#6366f1" radius={[0, 6, 6, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="card p-6">
          <h2 className="section-title mb-4">Platform Summary</h2>
          <div className="space-y-4">
            {[
              { label: 'Click-through Rate', value: stats.totalImpressions > 0 ? `${((stats.totalClicks / stats.totalImpressions) * 100).toFixed(2)}%` : '0%', bar: stats.totalImpressions > 0 ? (stats.totalClicks / stats.totalImpressions) * 100 : 0, color: 'bg-indigo-500' },
              { label: 'Campaigns per User', value: stats.totalUsers > 0 ? (stats.totalCampaigns / stats.totalUsers).toFixed(1) : '0', bar: Math.min((stats.totalCampaigns / Math.max(stats.totalUsers, 1)) * 20, 100), color: 'bg-emerald-500' },
              { label: 'Placements per Website', value: stats.totalWebsites > 0 ? (stats.totalPlacements / stats.totalWebsites).toFixed(1) : '0', bar: Math.min((stats.totalPlacements / Math.max(stats.totalWebsites, 1)) * 20, 100), color: 'bg-amber-500' },
            ].map(({ label, value, bar, color }) => (
              <div key={label}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-gray-600">{label}</span>
                  <span className="font-semibold text-gray-900">{value}</span>
                </div>
                <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                  <div className={`h-full ${color} rounded-full transition-all`} style={{ width: `${Math.min(bar, 100)}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend-2/src/app/pages/admin/stats/stats.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../../core/services/api.service';
import { StatCardComponent } from '../../../shared/components/stat-card/stat-card.component';

@Component({
  selector: 'app-admin-stats',
  standalone: true,
  imports: [
    CommonModule,
    StatCardComponent
  ],
  templateUrl: './stats.component.html'
})
export class StatsComponent implements OnInit {
  stats: any = null;

  private api = inject(ApiService);

  ngOnInit() {
    this.api.admin.getStats().subscribe({
      next: (res) => {
        this.stats = res;
      }
    });
  }

  get revenueData(): any[] {
    if (!this.stats) return [];
    
    const platform = Number(this.stats.totalPlatformRevenue);
    const network = Number(this.stats.totalNetworkRevenue);
    const publisher = network * 3.5;
    const maxVal = Math.max(platform, network, publisher, 1);

    return [
      { name: 'Platform (10%)', value: platform, percentage: (platform / maxVal) * 100 },
      { name: 'Network (20%)', value: network, percentage: (network / maxVal) * 100 },
      { name: 'Publisher (70%)', value: publisher, percentage: (publisher / maxVal) * 100 },
    ];
  }

  get ctrPercentage(): string {
    if (!this.stats) return '0%';
    const ctr = this.stats.totalImpressions > 0 ? (this.stats.totalClicks / this.stats.totalImpressions) * 100 : 0;
    return `${ctr.toFixed(2)}%`;
  }

  get ctrBarVal(): number {
    if (!this.stats) return 0;
    return this.stats.totalImpressions > 0 ? (this.stats.totalClicks / this.stats.totalImpressions) * 100 : 0;
  }

  get campaignsPerUser(): string {
    if (!this.stats) return '0';
    const val = this.stats.totalUsers > 0 ? (this.stats.totalCampaigns / this.stats.totalUsers) : 0;
    return val.toFixed(1);
  }

  get campaignsPerUserBarVal(): number {
    if (!this.stats) return 0;
    const val = this.stats.totalUsers > 0 ? (this.stats.totalCampaigns / this.stats.totalUsers) : 0;
    return Math.min(val * 20, 100);
  }

  get placementsPerWebsite(): string {
    if (!this.stats) return '0';
    const val = this.stats.totalWebsites > 0 ? (this.stats.totalPlacements / this.stats.totalWebsites) : 0;
    return val.toFixed(1);
  }

  get placementsPerWebsiteBarVal(): number {
    if (!this.stats) return 0;
    const val = this.stats.totalWebsites > 0 ? (this.stats.totalPlacements / this.stats.totalWebsites) : 0;
    return Math.min(val * 20, 100);
  }
}

<div *ngIf="!stats" class="animate-pulse space-y-4">
  <div class="h-8 bg-gray-200 rounded w-48"></div>
  <div class="grid grid-cols-4 gap-4">
    <div *ngFor="let i of [1, 2, 3, 4, 5, 6, 7, 8]" class="h-24 bg-gray-200 rounded-2xl"></div>
  </div>
</div>

<div *ngIf="stats" class="space-y-6">
  <div>
    <h1 class="page-title">Platform Statistics</h1>
    <p class="text-sm text-gray-500 mt-0.5">Real-time overview of the AdSphere platform</p>
  </div>

  <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
    <app-stat-card label="Total Users" [value]="stats.totalUsers" icon="users" color="indigo"></app-stat-card>
    <app-stat-card label="Total Websites" [value]="stats.totalWebsites" icon="globe" color="cyan"></app-stat-card>
    <app-stat-card label="Total Campaigns" [value]="stats.totalCampaigns" icon="megaphone" color="amber"></app-stat-card>
    <app-stat-card label="Total Placements" [value]="stats.totalPlacements" icon="layout-grid" color="violet"></app-stat-card>
  </div>

  <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
    <app-stat-card label="Total Impressions" [value]="stats.totalImpressions | number" icon="eye" color="indigo"></app-stat-card>
    <app-stat-card label="Total Clicks" [value]="stats.totalClicks | number" icon="mouse-pointer-click" color="emerald"></app-stat-card>
    <app-stat-card label="Platform Revenue" [value]="'$' + (stats.totalPlatformRevenue | number:'1.4-4')" icon="dollar-sign" color="rose"></app-stat-card>
    <app-stat-card label="Network Revenue" [value]="'$' + (stats.totalNetworkRevenue | number:'1.4-4')" icon="trending-up" color="violet"></app-stat-card>
  </div>

  <div class="grid grid-cols-1 xl:grid-cols-2 gap-6">
    <div class="card p-6">
      <h2 class="section-title mb-4">Revenue Distribution</h2>
      <div class="space-y-6">
        <div *ngFor="let item of revenueData" class="space-y-1">
          <div class="flex justify-between text-xs font-semibold text-gray-500 uppercase tracking-wide">
            <span>{{ item.name }}</span>
            <span class="text-gray-900">\${{ item.value | number:'1.4-4' }}</span>
          </div>
          <div class="h-6 bg-gray-50 rounded-lg overflow-hidden border border-gray-100 relative flex items-center px-1">
            <div class="h-full bg-indigo-600 rounded transition-all" [style.width.%]="item.percentage"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="card p-6">
      <h2 class="section-title mb-4">Platform Summary</h2>
      <div class="space-y-4">
        <div>
          <div class="flex justify-between text-sm mb-1">
            <span class="text-gray-600">Click-through Rate</span>
            <span class="font-semibold text-gray-900">{{ ctrPercentage }}</span>
          </div>
          <div class="h-2 bg-gray-100 rounded-full overflow-hidden">
            <div class="h-full bg-indigo-500 rounded-full transition-all" [style.width.%]="ctrBarVal"></div>
          </div>
        </div>

        <div>
          <div class="flex justify-between text-sm mb-1">
            <span class="text-gray-600">Campaigns per User</span>
            <span class="font-semibold text-gray-900">{{ campaignsPerUser }}</span>
          </div>
          <div class="h-2 bg-gray-100 rounded-full overflow-hidden">
            <div class="h-full bg-emerald-500 rounded-full transition-all" [style.width.%]="campaignsPerUserBarVal"></div>
          </div>
        </div>

        <div>
          <div class="flex justify-between text-sm mb-1">
            <span class="text-gray-600">Placements per Website</span>
            <span class="font-semibold text-gray-900">{{ placementsPerWebsite }}</span>
          </div>
          <div class="h-2 bg-gray-100 rounded-full overflow-hidden">
            <div class="h-full bg-amber-500 rounded-full transition-all" [style.width.%]="placementsPerWebsiteBarVal"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
